<?php

namespace Database\Seeders\Central;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::updateOrCreate(['iso' => 'AX'], ['name' => 'Islas Gland']);
        Country::updateOrCreate(['iso' => 'AL'], ['name' => 'Albania']);
        Country::updateOrCreate(['iso' => 'DE'], ['name' => 'Alemania']);
        Country::updateOrCreate(['iso' => 'AD'], ['name' => 'Andorra']);
        Country::updateOrCreate(['iso' => 'AO'], ['name' => 'Angola']);
        Country::updateOrCreate(['iso' => 'AI'], ['name' => 'Anguilla']);
        Country::updateOrCreate(['iso' => 'AQ'], ['name' => 'Antártida']);
        Country::updateOrCreate(['iso' => 'AG'], ['name' => 'Antigua y Barbuda']);
        Country::updateOrCreate(['iso'  => 'AN'], ['name' => 'Antillas Holandesas']);
        Country::updateOrCreate(['iso'  => 'SA'], ['name' => 'Arabia Saudí']);
        Country::updateOrCreate(['iso'  => 'DZ'], ['name' => 'Argelia']);
        Country::updateOrCreate(['iso'  => 'AR'], ['name' => 'Argentina']);
        Country::updateOrCreate(['iso'  => 'AM'], ['name' => 'Armenia']);
        Country::updateOrCreate(['iso'  => 'AW'], ['name' => 'Aruba']);
        Country::updateOrCreate(['iso'  => 'AU'], ['name' => 'Australia']);
        Country::updateOrCreate(['iso'  => 'AT'], ['name' => 'Austria']);
        Country::updateOrCreate(['iso'  => 'AZ'], ['name' => 'Azerbaiyán']);
        Country::updateOrCreate(['iso'  => 'BS'], ['name' => 'Bahamas']);
        Country::updateOrCreate(['iso'  => 'BH'], ['name' => 'Bahréin']);
        Country::updateOrCreate(['iso'  => 'BD'], ['name' => 'Bangladesh']);
        Country::updateOrCreate(['iso'  => 'BB'], ['name' => 'Barbados']);
        Country::updateOrCreate(['iso'  => 'BY'], ['name' => 'Bielorrusia']);
        Country::updateOrCreate(['iso'  => 'BE'], ['name' => 'Bélgica']);
        Country::updateOrCreate(['iso'  => 'BZ'], ['name' => 'Belice']);
        Country::updateOrCreate(['iso'  => 'BJ'], ['name' => 'Benin']);
        Country::updateOrCreate(['iso'  => 'BM'], ['name' => 'Bermudas']);
        Country::updateOrCreate(['iso'  => 'BT'], ['name' => 'Bhután']);
        Country::updateOrCreate(['iso'  => 'BO'], ['name' => 'Bolivia']);
        Country::updateOrCreate(['iso'  => 'BA'], ['name' => 'Bosnia y Herzegovina']);
        Country::updateOrCreate(['iso'  => 'BW'], ['name' => 'Botsuana']);
        Country::updateOrCreate(['iso'  => 'BV'], ['name' => 'Isla Bouvet']);
        Country::updateOrCreate(['iso'  => 'BR'], ['name' => 'Brasil']);
        Country::updateOrCreate(['iso'  => 'BN'], ['name' => 'Brunéi']);
        Country::updateOrCreate(['iso'  => 'BG'], ['name' => 'Bulgaria']);
        Country::updateOrCreate(['iso'  => 'BF'], ['name' => 'Burkina Faso']);
        Country::updateOrCreate(['iso'  => 'BI'], ['name' => 'Burundi']);
        Country::updateOrCreate(['iso'  => 'CV'], ['name' => 'Cabo Verde']);
        Country::updateOrCreate(['iso'  => 'KY'], ['name' => 'Islas Caimán']);
        Country::updateOrCreate(['iso'  => 'KH'], ['name' => 'Camboya']);
        Country::updateOrCreate(['iso'  => 'CM'], ['name' => 'Camerún']);
        Country::updateOrCreate(['iso'  => 'CA'], ['name' => 'Canadá']);
        Country::updateOrCreate(['iso'  => 'CF'], ['name' => 'República Centroafricana']);
        Country::updateOrCreate(['iso'  => 'TD'], ['name' => 'Chad']);
        Country::updateOrCreate(['iso'  => 'CZ'], ['name' => 'República Checa']);
        Country::updateOrCreate(['iso'  => 'CL'], ['name' => 'Chile']);
        Country::updateOrCreate(['iso'  => 'CN'], ['name' => 'China']);
        Country::updateOrCreate(['iso'  => 'CY'], ['name' => 'Chipre']);
        Country::updateOrCreate(['iso'  => 'CX'], ['name' => 'Isla de Navidad']);
        Country::updateOrCreate(['iso'  => 'VA'], ['name' => 'Ciudad del Vaticano']);
        Country::updateOrCreate(['iso'  => 'CC'], ['name' => 'Islas Cocos']);
        Country::updateOrCreate(['iso'  => 'CO'], ['name' => 'Colombia']);
        Country::updateOrCreate(['iso'  => 'KM'], ['name' => 'Comoras']);
        Country::updateOrCreate(['iso'  => 'CD'], ['name' => 'República Democrática del Congo']);
        Country::updateOrCreate(['iso'  => 'CG'], ['name' => 'Congo']);
        Country::updateOrCreate(['iso'  => 'CK'], ['name' => 'Islas Cook']);
        Country::updateOrCreate(['iso'  => 'KP'], ['name' => 'Corea del Norte']);
        Country::updateOrCreate(['iso'  => 'KR'], ['name' => 'Corea del Sur']);
        Country::updateOrCreate(['iso'  => 'CI'], ['name' => 'Costa de Marfil']);
        Country::updateOrCreate(['iso'  => 'CR'], ['name' => 'Costa Rica']);
        Country::updateOrCreate(['iso'  => 'HR'], ['name' => 'Croacia']);
        Country::updateOrCreate(['iso'  => 'CU'], ['name' => 'Cuba']);
        Country::updateOrCreate(['iso'  => 'DK'], ['name' => 'Dinamarca']);
        Country::updateOrCreate(['iso'  => 'DM'], ['name' => 'Dominica']);
        Country::updateOrCreate(['iso'  => 'DO'], ['name' => 'República Dominicana']);
        Country::updateOrCreate(['iso'  => 'EC'], ['name' => 'Ecuador']);
        Country::updateOrCreate(['iso'  => 'EG'], ['name' => 'Egipto']);
        Country::updateOrCreate(['iso'  => 'SV'], ['name' => 'El Salvador']);
        Country::updateOrCreate(['iso'  => 'AE'], ['name' => 'Emiratos Árabes Unidos']);
        Country::updateOrCreate(['iso'  => 'ER'], ['name' => 'Eritrea']);
        Country::updateOrCreate(['iso'  => 'SK'], ['name' => 'Eslovaquia']);
        Country::updateOrCreate(['iso'  => 'SI'], ['name' => 'Eslovenia']);
        Country::updateOrCreate(['iso'  => 'ES'], ['name' => 'España']);
        Country::updateOrCreate(['iso'  => 'UM'], ['name' => 'Islas ultramarinas de Estados Unidos']);
        Country::updateOrCreate(['iso'  => 'US'], ['name' => 'Estados Unidos']);
        Country::updateOrCreate(['iso'  => 'EE'], ['name' => 'Estonia']);
        Country::updateOrCreate(['iso'  => 'ET'], ['name' => 'Etiopía']);
        Country::updateOrCreate(['iso'  => 'FO'], ['name' => 'Islas Feroe']);
        Country::updateOrCreate(['iso'  => 'PH'], ['name' => 'Filipinas']);
        Country::updateOrCreate(['iso'  => 'FI'], ['name' => 'Finlandia']);
        Country::updateOrCreate(['iso'  => 'FJ'], ['name' => 'Fiyi']);
        Country::updateOrCreate(['iso'  => 'FR'], ['name' => 'Francia']);
        Country::updateOrCreate(['iso'  => 'GA'], ['name' => 'Gabón']);
        Country::updateOrCreate(['iso'  => 'GM'], ['name' => 'Gambia']);
        Country::updateOrCreate(['iso'  => 'GE'], ['name' => 'Georgia']);
        Country::updateOrCreate(['iso'  => 'GS'], ['name' => 'Islas Georgias del Sur y Sandwich del Sur']);
        Country::updateOrCreate(['iso'  => 'GH'], ['name' => 'Ghana']);
        Country::updateOrCreate(['iso'  => 'GI'], ['name' => 'Gibraltar']);
        Country::updateOrCreate(['iso'  => 'GD'], ['name' => 'Granada']);
        Country::updateOrCreate(['iso'  => 'GR'], ['name' => 'Grecia']);
        Country::updateOrCreate(['iso'  => 'GL'], ['name' => 'Groenlandia']);
        Country::updateOrCreate(['iso'  => 'GP'], ['name' => 'Guadalupe']);
        Country::updateOrCreate(['iso'  => 'GU'], ['name' => 'Guam']);
        Country::updateOrCreate(['iso'  => 'GT'], ['name' => 'Guatemala']);
        Country::updateOrCreate(['iso'  => 'GF'], ['name' => 'Guayana Francesa']);
        Country::updateOrCreate(['iso'  => 'GN'], ['name' => 'Guinea']);
        Country::updateOrCreate(['iso'  => 'GQ'], ['name' => 'Guinea Ecuatorial']);
        Country::updateOrCreate(['iso'  => 'GW'], ['name' => 'Guinea-Bissau']);
        Country::updateOrCreate(['iso'  => 'GY'], ['name' => 'Guyana']);
        Country::updateOrCreate(['iso' => 'HT'], ['name' => 'Haití']);
        Country::updateOrCreate(['iso' => 'HM'], ['name' => 'Islas Heard y McDonald']);
        Country::updateOrCreate(['iso' => 'HN'], ['name' => 'Honduras']);
        Country::updateOrCreate(['iso' => 'HK'], ['name' => 'Hong Kong']);
        Country::updateOrCreate(['iso' => 'HU'], ['name' => 'Hungría']);
        Country::updateOrCreate(['iso' => 'IN'], ['name' => 'India']);
        Country::updateOrCreate(['iso' => 'ID'], ['name' => 'Indonesia']);
        Country::updateOrCreate(['iso' => 'IR'], ['name' => 'Irán']);
        Country::updateOrCreate(['iso' => 'IQ'], ['name' => 'Iraq']);
        Country::updateOrCreate(['iso' => 'IE'], ['name' => 'Irlanda']);
        Country::updateOrCreate(['iso' => 'IS'], ['name' => 'Islandia']);
        Country::updateOrCreate(['iso' => 'IL'], ['name' => 'Israel']);
        Country::updateOrCreate(['iso' => 'IT'], ['name' => 'Italia']);
        Country::updateOrCreate(['iso' => 'JM'], ['name' => 'Jamaica']);
        Country::updateOrCreate(['iso' => 'JP'], ['name' => 'Japón']);
        Country::updateOrCreate(['iso' => 'JO'], ['name' => 'Jordania']);
        Country::updateOrCreate(['iso' => 'KZ'], ['name' => 'Kazajstán']);
        Country::updateOrCreate(['iso' => 'KE'], ['name' => 'Kenia']);
        Country::updateOrCreate(['iso' => 'KG'], ['name' => 'Kirguistán']);
        Country::updateOrCreate(['iso' => 'KI'], ['name' => 'Kiribati']);
        Country::updateOrCreate(['iso' => 'KW'], ['name' => 'Kuwait']);
        Country::updateOrCreate(['iso' => 'LA'], ['name' => 'Laos']);
        Country::updateOrCreate(['iso' => 'LS'], ['name' => 'Lesotho']);
        Country::updateOrCreate(['iso' => 'LV'], ['name' => 'Letonia']);
        Country::updateOrCreate(['iso' => 'LB'], ['name' => 'Líbano']);
        Country::updateOrCreate(['iso' => 'LR'], ['name' => 'Liberia']);
        Country::updateOrCreate(['iso' => 'LY'], ['name' => 'Libia']);
        Country::updateOrCreate(['iso' => 'LI'], ['name' => 'Liechtenstein']);
        Country::updateOrCreate(['iso' => 'LT'], ['name' => 'Lituania']);
        Country::updateOrCreate(['iso' => 'LU'], ['name' => 'Luxemburgo']);
        Country::updateOrCreate(['iso' => 'MO'], ['name' => 'Macao']);
        Country::updateOrCreate(['iso' => 'MK'], ['name' => 'ARY Macedonia']);
        Country::updateOrCreate(['iso' => 'MG'], ['name' => 'Madagascar']);
        Country::updateOrCreate(['iso' => 'MY'], ['name' => 'Malasia']);
        Country::updateOrCreate(['iso' => 'MW'], ['name' => 'Malawi']);
        Country::updateOrCreate(['iso' => 'MV'], ['name' => 'Maldivas']);
        Country::updateOrCreate(['iso' => 'ML'], ['name' => 'Malí']);
        Country::updateOrCreate(['iso' => 'MT'], ['name' => 'Malta']);
        Country::updateOrCreate(['iso' => 'FK'], ['name' => 'Islas Malvinas']);
        Country::updateOrCreate(['iso' => 'MP'], ['name' => 'Islas Marianas del Norte']);
        Country::updateOrCreate(['iso' => 'MA'], ['name' => 'Marruecos']);
        Country::updateOrCreate(['iso' => 'MH'], ['name' => 'Islas Marshall']);
        Country::updateOrCreate(['iso' => 'MQ'], ['name' => 'Martinica']);
        Country::updateOrCreate(['iso' => 'MU'], ['name' => 'Mauricio']);
        Country::updateOrCreate(['iso' => 'MR'], ['name' => 'Mauritania']);
        Country::updateOrCreate(['iso' => 'YT'], ['name' => 'Mayotte']);
        Country::updateOrCreate(['iso' => 'MX'], ['name' => 'México']);
        Country::updateOrCreate(['iso' => 'FM'], ['name' => 'Micronesia']);
        Country::updateOrCreate(['iso' => 'MD'], ['name' => 'Moldavia']);
        Country::updateOrCreate(['iso' => 'MC'], ['name' => 'Mónaco']);
        Country::updateOrCreate(['iso' => 'MN'], ['name' => 'Mongolia']);
        Country::updateOrCreate(['iso' => 'MS'], ['name' => 'Montserrat']);
        Country::updateOrCreate(['iso' => 'MZ'], ['name' => 'Mozambique']);
        Country::updateOrCreate(['iso' => 'MM'], ['name' => 'Myanmar']);
        Country::updateOrCreate(['iso' => 'NA'], ['name' => 'Namibia']);
        Country::updateOrCreate(['iso' => 'NR'], ['name' => 'Nauru']);
        Country::updateOrCreate(['iso' => 'NP'], ['name' => 'Nepal']);
        Country::updateOrCreate(['iso' => 'NI'], ['name' => 'Nicaragua']);
        Country::updateOrCreate(['iso' => 'NE'], ['name' => 'Níger']);
        Country::updateOrCreate(['iso' => 'NG'], ['name' => 'Nigeria']);
        Country::updateOrCreate(['iso' => 'NU'], ['name' => 'Niue']);
        Country::updateOrCreate(['iso' => 'NF'], ['name' => 'Isla Norfolk']);
        Country::updateOrCreate(['iso' => 'NO'], ['name' => 'Noruega']);
        Country::updateOrCreate(['iso' => 'NC'], ['name' => 'Nueva Caledonia']);
        Country::updateOrCreate(['iso' => 'NZ'], ['name' => 'Nueva Zelanda']);
        Country::updateOrCreate(['iso' => 'OM'], ['name' => 'Omán']);
        Country::updateOrCreate(['iso' => 'NL'], ['name' => 'Países Bajos']);
        Country::updateOrCreate(['iso' => 'PK'], ['name' => 'Pakistán']);
        Country::updateOrCreate(['iso' => 'PW'], ['name' => 'Palau']);
        Country::updateOrCreate(['iso' => 'PS'], ['name' => 'Palestina']);
        Country::updateOrCreate(['iso' => 'PA'], ['name' => 'Panamá']);
        Country::updateOrCreate(['iso' => 'PG'], ['name' => 'Papúa Nueva Guinea']);
        Country::updateOrCreate(['iso' => 'PY'], ['name' => 'Paraguay']);
        Country::updateOrCreate(['iso' => 'PE'], ['name' => 'Perú']);
        Country::updateOrCreate(['iso' => 'PN'], ['name' => 'Islas Pitcairn']);
        Country::updateOrCreate(['iso' => 'PF'], ['name' => 'Polinesia Francesa']);
        Country::updateOrCreate(['iso' => 'PL'], ['name' => 'Polonia']);
        Country::updateOrCreate(['iso' => 'PT'], ['name' => 'Portugal']);
        Country::updateOrCreate(['iso' => 'PR'], ['name' => 'Puerto Rico']);
        Country::updateOrCreate(['iso' => 'QA'], ['name' => 'Qatar']);
        Country::updateOrCreate(['iso' => 'GB'], ['name' => 'Reino Unido']);
        Country::updateOrCreate(['iso' => 'RE'], ['name' => 'Reunión']);
        Country::updateOrCreate(['iso' => 'RW'], ['name' => 'Ruanda']);
        Country::updateOrCreate(['iso' => 'RO'], ['name' => 'Rumania']);
        Country::updateOrCreate(['iso' => 'RU'], ['name' => 'Rusia']);
        Country::updateOrCreate(['iso' => 'EH'], ['name' => 'Sahara Occidental']);
        Country::updateOrCreate(['iso' => 'SB'], ['name' => 'Islas Salomón']);
        Country::updateOrCreate(['iso' => 'WS'], ['name' => 'Samoa']);
        Country::updateOrCreate(['iso' => 'AS'], ['name' => 'Samoa Americana']);
        Country::updateOrCreate(['iso' => 'KN'], ['name' => 'San Cristóbal y Nevis']);
        Country::updateOrCreate(['iso' => 'SM'], ['name' => 'San Marino']);
        Country::updateOrCreate(['iso' => 'PM'], ['name' => 'San Pedro y Miquelón']);
        Country::updateOrCreate(['iso' => 'VC'], ['name' => 'San Vicente y las Granadinas']);
        Country::updateOrCreate(['iso' => 'SH'], ['name' => 'Santa Helena']);
        Country::updateOrCreate(['iso' => 'LC'], ['name' => 'Santa Lucía']);
        Country::updateOrCreate(['iso' => 'ST'], ['name' => 'Santo Tomé y Príncipe']);
        Country::updateOrCreate(['iso' => 'SN'], ['name' => 'Senegal']);
        Country::updateOrCreate(['iso' => 'CS'], ['name' => 'Serbia y Montenegro']);
        Country::updateOrCreate(['iso' => 'SC'], ['name' => 'Seychelles']);
        Country::updateOrCreate(['iso' => 'SL'], ['name' => 'Sierra Leona']);
        Country::updateOrCreate(['iso' => 'SG'], ['name' => 'Singapur']);
        Country::updateOrCreate(['iso' => 'SY'], ['name' => 'Siria']);
        Country::updateOrCreate(['iso' => 'SO'], ['name' => 'Somalia']);
        Country::updateOrCreate(['iso' => 'LK'], ['name' => 'Sri Lanka']);
        Country::updateOrCreate(['iso' => 'SZ'], ['name' => 'Suazilandia']);
        Country::updateOrCreate(['iso' => 'ZA'], ['name' => 'Sudáfrica']);
        Country::updateOrCreate(['iso' => 'SD'], ['name' => 'Sudán']);
        Country::updateOrCreate(['iso' => 'SE'], ['name' => 'Suecia']);
        Country::updateOrCreate(['iso' => 'CH'], ['name' => 'Suiza']);
        Country::updateOrCreate(['iso' => 'SR'], ['name' => 'Surinam']);
        Country::updateOrCreate(['iso' => 'SJ'], ['name' => 'Svalbard y Jan Mayen']);
        Country::updateOrCreate(['iso' => 'TH'], ['name' => 'Tailandia']);
        Country::updateOrCreate(['iso' => 'TW'], ['name' => 'Taiwán']);
        Country::updateOrCreate(['iso' => 'TZ'], ['name' => 'Tanzania']);
        Country::updateOrCreate(['iso' => 'TJ'], ['name' => 'Tayikistán']);
        Country::updateOrCreate(['iso' => 'IO'], ['name' => 'Territorio Británico del Océano Índico']);
        Country::updateOrCreate(['iso' => 'TF'], ['name' => 'Territorios Australes Franceses']);
        Country::updateOrCreate(['iso' => 'TL'], ['name' => 'Timor Oriental']);
        Country::updateOrCreate(['iso' => 'TG'], ['name' => 'Togo']);
        Country::updateOrCreate(['iso' => 'TK'], ['name' => 'Tokelau']);
        Country::updateOrCreate(['iso' => 'TO'], ['name' => 'Tonga']);
        Country::updateOrCreate(['iso' => 'TT'], ['name' => 'Trinidad y Tobago']);
        Country::updateOrCreate(['iso' => 'TN'], ['name' => 'Túnez']);
        Country::updateOrCreate(['iso' => 'TC'], ['name' => 'Islas Turcas y Caicos']);
        Country::updateOrCreate(['iso' => 'TM'], ['name' => 'Turkmenistán']);
        Country::updateOrCreate(['iso' => 'TR'], ['name' => 'Turquía']);
        Country::updateOrCreate(['iso' => 'TV'], ['name' => 'Tuvalu']);
        Country::updateOrCreate(['iso' => 'UA'], ['name' => 'Ucrania']);
        Country::updateOrCreate(['iso' => 'UG'], ['name' => 'Uganda']);
        Country::updateOrCreate(['iso' => 'UY'], ['name' => 'Uruguay']);
        Country::updateOrCreate(['iso' => 'UZ'], ['name' => 'Uzbekistán']);
        Country::updateOrCreate(['iso' => 'VU'], ['name' => 'Vanuatu']);
        Country::updateOrCreate(['iso' => 'VE'], ['name' => 'Venezuela']);
        Country::updateOrCreate(['iso' => 'VN'], ['name' => 'Vietnam']);
        Country::updateOrCreate(['iso' => 'VG'], ['name' => 'Islas Vírgenes Británicas']);
        Country::updateOrCreate(['iso' => 'VI'], ['name' => 'Islas Vírgenes de los Estados Unidos']);
        Country::updateOrCreate(['iso' => 'WF'], ['name' => 'Wallis y Futuna']);
        Country::updateOrCreate(['iso' => 'YE'], ['name' => 'Yemen']);
        Country::updateOrCreate(['iso' => 'DJ'], ['name' => 'Yibuti']);
        Country::updateOrCreate(['iso' => 'ZM'], ['name' => 'Zambia']);
        Country::updateOrCreate(['iso' => 'ZW'], ['name' => 'Zimbabue']);
    }
}
